name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    release:
        runs-on: windows-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - run: npm ci

            - name: Build
              run: npm run build
              env:
                  GH_TOKEN_RO: ${{ secrets.GH_TOKEN_RO }}

            - name: Publish
              run: npx electron-builder --win --publish always
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
